apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: amazon-clone-k8s-deployment
spec:
  selector:
    matchLabels:
      app: amazon-clone
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: amazon-clone
    spec:
      containers:
        - name: amazon-clone
          image: syedwasifabbas/amazon-clone:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: amazonclone-k8ssvc
spec:
  selector:
    app: amazon-clone
  ports:
    - protocol: "TCP"
      port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
  type: NodePort # type of the service.